version: "3.9"
services:
  gateway:
    container_name: gateway
    build:      
      context: ./ParadiseCommerce.Web
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq3
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:4000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=DK2VDPQe3t7C8WdC
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "4000:4000"
    volumes:
      - ~/.aspnet/https:/https:ro
  ordering:
    container_name: ordering
    build:      
      context: ./ParadiseCommerce.Services.Ordering
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq3
      - mongodb_container
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
  rabbitmq3:
    container_name: "rabbitmq-3"
    image: rabbitmq:3.8-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: